### PR TITLE
First Commit

### PR DESCRIPTION
**Pull request by Aakarsh00**

### CODE REVIEW

**Comment by srivasPankhuri** [comment]
Add the project file inside the model folder. You can see other closed PRs for reference.

**Comment by srivasPankhuri** [comment]
@Aakarsh00 do the changes as mentioned only then we will be able to merge this PR and assign you other projects

**Comment by Aakarsh00** [comment]
@srivasPankhuri can you please elaborate the issue.

**Comment by srivasPankhuri** [comment]
@Aakarsh00 your Loan Prediction.ipynb should have the entire content of that file rather than a URL. Look at some merged PRs to get an idea.

**Comment by divik2510** [comment]
Hello @Aakarsh00! 
closing this pull request as you haven't provided proper files.

**Pull request closed without merging**
